language: 
  - cpp


install:
  - sudo apt-get update
  - sudo apt-get install cmake

script:
  - chmod 755 build_all.sh && ./build_all.sh
  - cd cmake_build/tests
  - ./MyTester
  - cd ..
  - find . -name \*.gcno
  - find . -name \*.gcda

after_success:
  - echo "Build finished successfully"
