language: 
  - cpp

compiler:
  - gcc

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update -q
  - sudo apt-get install gcc-4.8 -y

install:
  - sudo apt-get install cmake
  - sudo apt-get install libgtest-dev
  - cd /usr/src/gtest && sudo cmake CMakeLists.txt && sudo make && sudo cp *.a /usr/local/lib/ && cd -
 
script:
  - chmod 755 build_all.sh && ./build_all.sh
  - cd cmake_build/tests
  - ./MyTester
  - cd ..
  - find . -name \*.gcno
  - find . -name \*.gcda
  - cd ..
after_success:
  - echo "Build finished successfully"
  - bash <(curl -s https://codecov.io/bash)
